id: I9B21A2A4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T05:01:19+00:00'
last_modified: '2022-06-08T08:12:16.455657+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21297
  title: རྩ་ཤེས་ཊཱིཀ་ཆེན་གྱི་བསྡུས་དོན་ལྟ་བ་དྲན་པའི་ཆུ་རྒྱུན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    70A7:
      image_group_id: I1KG21668
      title: ''
      total_pages: 450
      order: 1
      base_file: 70A7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
